In [1]:
import pandas as pd
df = pd.read_csv(filepath_or_buffer='/kaggle/input/visa-application-for-peoples-the-owlrd/visa_number_in_japan.csv')
df.head()

,Year,Regional code,Country,Number of issued,Number of issued_numerical,Travel certificate,Diplomacy,Public use,Passing,Short -term stay,...,identification,Specific_housework employee,Specified_short term,Specific_profit representative staff,Specific_working holiday,Specified_Amasport,"Specific_Japanese spouse, etc.","Specific_Permanent resident's spouse, etc.",Specified_Distingant,Specific_Others
0,2017,0,total,5869012,741415,389.0,4862.0,16402.0,8518,5392838,...,53552,122.0,NaN,49.0,15521.0,77.0,10227,2181.0,16945,8431.0
1,2017,40,Afghanistan,1005,46,0.0,14.0,112.0,0,224,...,13,0.0,NaN,0.0,0.0,0.0,2,3.0,8,0.0
2,2017,80,Albania,252,7,0.0,0.0,2.0,1,200,...,0,0.0,NaN,0.0,0.0,0.0,0,0.0,0,0.0
3,2017,120,Algeria,899,19,0.0,8.0,11.0,3,813,...,2,0.0,NaN,0.0,0.0,0.0,1,1.0,0,0.0
4,2017,200,Andra,5,0,0.0,0.0,0.0,0,0,...,0,0.0,NaN,0.0,0.0,0.0,0,0.0,0,0.0

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1945 entries, 0 to 1944
Data columns (total 48 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Year                                        1945 non-null   int64
 1   Regional code                               1945 non-null   int64
 2   Country                                     1945 non-null   object
 3   Number of issued                            1945 non-null   int64
 4   Number of issued_numerical                  1945 non-null   int64
 5   Travel certificate                          1913 non-null   float64
 6   Diplomacy                                   1913 non-null   float64
 7   Public use                                  1913 non-null   float64
 8   Passing                                     1945 non-null   int64
 9   Short -term stay                            1945 non-null   int64
 10  Staying in medical care                     1438 non-null   float64
 11  Advanced profession                         1230 non-null   float64
 12  Employment                                  1945 non-null   int64
 13  Employment_Professor                        1913 non-null   float64
 14  Employment_Art                              1913 non-null   float64
 15  Employment_religion                         1913 non-null   float64
 16  Employment_Report                           1913 non-null   float64
 17  Employment_Management / Management          1913 non-null   float64
 18  Employment_Law accounting                   1913 non-null   float64
 19  Employment_Medical care                     1913 non-null   float64
 20  Employment_Research                         1913 non-null   float64
 21  Employment_Education                        1913 non-null   float64
 22  Employment_Country                          607 non-null    float64
 23  Employment_Technology                       1306 non-null   float64
 24  Employment_Humanities International         1338 non-null   float64
 25  Employment_C corporate rotation             1913 non-null   float64
 26  Employment_show                             1945 non-null   int64
 27  Employment_Skills                           1913 non-null   float64
 28  Employment_Steng (new)                      202 non-null    float64
 29  Employment_Nursing care                     202 non-null    float64
 30  Ordinary                                    1945 non-null   int64
 31  General_Cultural activity                   1913 non-null   float64
 32  General_Studying abroad                     1913 non-null   float64
 33  General_Arademy                             1130 non-null   float64
 34  General_Training                            1945 non-null   int64
 35  General_Family stay                         1913 non-null   float64
 36  General_Stifying 1 I                        1645 non-null   float64
 37  General_Steng 1                             1645 non-null   float64
 38  identification                              1945 non-null   int64
 39  Specific_housework employee                 1913 non-null   float64
 40  Specified_short term                        63 non-null     float64
 41  Specific_profit representative staff        1913 non-null   float64
 42  Specific_working holiday                    1913 non-null   float64
 43  Specified_Amasport                          1913 non-null   float64
 44  Specific_Japanese spouse, etc.              1945 non-null   int64
 45  Specific_Permanent resident's spouse, etc.  1913 non-null   float64
 46  Specified_Distingant                        1945 non-null   int64
 47  Specific_Others                             1913 non-null   float64
dtypes: float64(34), int64(13), object(1)
memory usage: 729.5+ KB

In [3]:
from plotly.express import scatter
scatter(data_frame=df['Year'].value_counts(dropna=False).to_frame().reset_index(), x='Year', y='count')

In [4]:
y2017_df = df[df['Year'] == 2017].copy().drop(columns=['Year'])
y2017_df.head()

,Regional code,Country,Number of issued,Number of issued_numerical,Travel certificate,Diplomacy,Public use,Passing,Short -term stay,Staying in medical care,...,identification,Specific_housework employee,Specified_short term,Specific_profit representative staff,Specific_working holiday,Specified_Amasport,"Specific_Japanese spouse, etc.","Specific_Permanent resident's spouse, etc.",Specified_Distingant,Specific_Others
0,0,total,5869012,741415,389.0,4862.0,16402.0,8518,5392838,1383.0,...,53552,122.0,NaN,49.0,15521.0,77.0,10227,2181.0,16945,8431.0
1,40,Afghanistan,1005,46,0.0,14.0,112.0,0,224,0.0,...,13,0.0,NaN,0.0,0.0,0.0,2,3.0,8,0.0
2,80,Albania,252,7,0.0,0.0,2.0,1,200,0.0,...,0,0.0,NaN,0.0,0.0,0.0,0,0.0,0,0.0
3,120,Algeria,899,19,0.0,8.0,11.0,3,813,0.0,...,2,0.0,NaN,0.0,0.0,0.0,1,1.0,0,0.0
4,200,Andra,5,0,0.0,0.0,0.0,0,0,0.0,...,0,0.0,NaN,0.0,0.0,0.0,0,0.0,0,0.0

In [5]:
df['Regional code'].value_counts()

Regional code
0       12
1440    12
7640    12
1560    12
1580    12
        ..
3440     4
2390     3
1781     2
8071     2
8265     1
Name: count, Length: 214, dtype: int64