In [1]:
import pandas as pd
df = pd.read_csv(filepath_or_buffer='/kaggle/input/student-anxiety-dataset/anxiety.csv', encoding = 'ISO-8859-1', index_col=['S. No.'],
                ).drop(columns=['highestleague'])
df['Timestamp'] = pd.to_datetime(df['Timestamp'], unit='D', origin='1899-12-30')
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13464 entries, 1 to 14250
Data columns (total 53 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Timestamp        13464 non-null  datetime64[ns]
 1   GAD1             13464 non-null  int64
 2   GAD2             13464 non-null  int64
 3   GAD3             13464 non-null  int64
 4   GAD4             13464 non-null  int64
 5   GAD5             13464 non-null  int64
 6   GAD6             13464 non-null  int64
 7   GAD7             13464 non-null  int64
 8   GADE             12815 non-null  object
 9   SWL1             13464 non-null  int64
 10  SWL2             13464 non-null  int64
 11  SWL3             13464 non-null  int64
 12  SWL4             13464 non-null  int64
 13  SWL5             13464 non-null  int64
 14  Game             13464 non-null  object
 15  Platform         13464 non-null  object
 16  Hours            13434 non-null  float64
 17  earnings         13464 non-null  object
 18  whyplay          13464 non-null  object
 19  League           11626 non-null  object
 20  streams          13364 non-null  float64
 21  SPIN1            13340 non-null  float64
 22  SPIN2            13310 non-null  float64
 23  SPIN3            13324 non-null  float64
 24  SPIN4            13305 non-null  float64
 25  SPIN5            13298 non-null  float64
 26  SPIN6            13308 non-null  float64
 27  SPIN7            13326 non-null  float64
 28  SPIN8            13320 non-null  float64
 29  SPIN9            13306 non-null  float64
 30  SPIN10           13304 non-null  float64
 31  SPIN11           13277 non-null  float64
 32  SPIN12           13296 non-null  float64
 33  SPIN13           13277 non-null  float64
 34  SPIN14           13308 non-null  float64
 35  SPIN15           13317 non-null  float64
 36  SPIN16           13317 non-null  float64
 37  SPIN17           13289 non-null  float64
 38  Narcissism       13441 non-null  float64
 39  Gender           13464 non-null  object
 40  Age              13464 non-null  int64
 41  Work             13426 non-null  object
 42  Degree           13464 non-null  object
 43  Birthplace       13464 non-null  object
 44  Residence        13464 non-null  object
 45  Reference        13449 non-null  object
 46  Playstyle        13464 non-null  object
 47  accept           13050 non-null  object
 48  GAD_T            13464 non-null  int64
 49  SWL_T            13464 non-null  int64
 50  SPIN_T           12814 non-null  float64
 51  Residence_ISO3   13354 non-null  object
 52  Birthplace_ISO3  13343 non-null  object
dtypes: datetime64[ns](1), float64(21), int64(15), object(16)
memory usage: 5.5+ MB

In [2]:
df.head()

,Timestamp,GAD1,GAD2,GAD3,GAD4,GAD5,GAD6,GAD7,GADE,SWL1,...,Birthplace,Residence,Reference,Playstyle,accept,GAD_T,SWL_T,SPIN_T,Residence_ISO3,Birthplace_ISO3
S. No.,,,,,,,,,,,,,,,,,,,,,
1,2015-02-17 00:06:17.568000256,0,0,0,0,1,0,0,Not difficult at all,3,...,USA,USA,Reddit,Singleplayer,Accept,1,23,5.0,USA,USA
2,2015-02-17 00:09:47.520000256,1,2,2,2,0,1,0,Somewhat difficult,3,...,USA,USA,Reddit,Multiplayer - online - with strangers,Accept,8,16,33.0,USA,USA
3,2015-02-17 00:55:35.040000000,0,2,2,0,0,3,1,Not difficult at all,2,...,Germany,Germany,Reddit,Singleplayer,Accept,8,17,31.0,DEU,DEU
4,2015-02-17 01:37:58.655999744,0,0,0,0,0,0,0,Not difficult at all,2,...,USA,USA,Reddit,Multiplayer - online - with online acquaintanc...,Accept,0,17,11.0,USA,USA
5,2015-02-17 02:08:51.072000256,2,1,2,2,2,3,2,Very difficult,2,...,USA,South Korea,Reddit,Multiplayer - online - with strangers,Accept,14,14,13.0,KOR,USA

In [3]:
df.nunique()

Timestamp          11734
GAD1                   4
GAD2                   4
GAD3                   4
GAD4                   4
GAD5                   4
GAD6                   4
GAD7                   4
GADE                   4
SWL1                   7
SWL2                   7
SWL3                   7
SWL4                   7
SWL5                   7
Game                  11
Platform               3
Hours                 84
earnings             314
whyplay              407
League              1455
streams               65
SPIN1                  5
SPIN2                  5
SPIN3                  5
SPIN4                  5
SPIN5                  5
SPIN6                  5
SPIN7                  5
SPIN8                  5
SPIN9                  5
SPIN10                 5
SPIN11                 5
SPIN12                 5
SPIN13                 5
SPIN14                 5
SPIN15                 5
SPIN16                 5
SPIN17                 5
Narcissism             5
Gender                 3
Age                   30
Work                   4
Degree                 5
Birthplace           126
Residence            109
Reference              4
Playstyle            298
accept                 1
GAD_T                 22
SWL_T                 31
SPIN_T                69
Residence_ISO3       107
Birthplace_ISO3      124
dtype: int64